"""
Settings for the Bangalore Restaurant Finder application
"""

# Default location (Bangalore city center)
DEFAULT_LATITUDE = 12.9716
DEFAULT_LONGITUDE = 77.5946
DEFAULT_ZOOM = 12

# Filter defaults
DEFAULT_MIN_RATING = 3.5
DEFAULT_MIN_VOTES = 50
DEFAULT_MAX_DISTANCE = 5
DEFAULT_TOP_N = 5

# Map settings
HEATMAP_RADIUS = 15
HEATMAP_GRADIENT = {0.4: "blue", 0.6: "cyan", 0.7: "lime", 0.8: "yellow", 1.0: "red"}

# Top cuisines in Bangalore (for quick selection)
TOP_CUISINES = [
    "North Indian",
    "Chinese",
    "South Indian",
    "Fast Food",
    "Continental",
    "Biryani",
    "Cafe",
    "Desserts",
    "Beverages",
    "Italian",
    "Street Food",
    "Bakery",
    "Pizza",
    "Burger",
    "Seafood",
]

ALL_CUISINES = [
    "North Indian",
    "Chinese",
    "South Indian",
    "Fast Food",
    "Biryani",
    "Continental",
    "Desserts",
    "Cafe",
    "Beverages",
    "Italian",
    "Bakery",
    "Street Food",
    "Pizza",
    "Burger",
    "Seafood",
    "Ice Cream",
    "Andhra",
    "Mughlai",
    "Rolls",
    "American",
    "Kerala",
    "Asian",
    "Momos",
    "Finger Food",
    "Juices",
    "Salad",
    "Arabian",
    "Kebab",
    "Mithai",
    "Thai",
    "Healthy Food",
    "Sandwich",
    "BBQ",
    "European",
    "Mangalorean",
    "Bengali",
    "Steak",
    "Mediterranean",
    "Mexican",
    "Tea",
    "Tibetan",
    "Japanese",
    "Hyderabadi",
    "Chettinad",
    "Rajasthani",
    "Lebanese",
    "Vietnamese",
    "Modern Indian",
    "Korean",
    "Maharashtrian",
    "Coffee",
    "Oriya",
    "Goan",
    "Malaysian",
    "Middle Eastern",
    "Gujarati",
    "Indonesian",
    "Turkish",
    "Bihari",
    "Charcoal Chicken",
    "French",
    "Nepalese",
    "Konkan",
    "Afghan",
    "North Eastern",
    "Wraps",
    "Burmese",
    "Lucknowi",
    "Tex-Mex",
    "Singaporean",
    "Sushi",
    "Spanish",
    "Bar Food",
    "Greek",
    "Kashmiri",
    "Iranian",
    "Awadhi",
    "Parsi",
    "Assamese",
    "Naga",
    "Grill",
    "Roast Chicken",
    "South American",
    "African",
    "Sri Lankan",
    "Paan",
    "Mongolian",
    "Portuguese",
    "Drinks Only",
    "Bubble Tea",
    "Afghani",
    "British",
    "German",
    "Tamil",
    "Bohri",
    "Vegan",
    "Russian",
    "Jewish",
    "Cantonese",
    "Australian",
    "Belgian",
    "Raw Meats",
    "Sindhi",
    "Pan Asian",
    "Hot dogs",
    "Indian",
    "Malwani",
]
